# Site settings
author: Todd Norton
title: Todd's TBD Blog
header-img: img/home-bg.png
email: toddmnorton@live.com
copyright_name: Todd Norton
description: > # this means to ignore newlines until "baseurl:"
  Not sure
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  toddmnortonCO

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
